export const INVALID_TOKEN = "INVALID_TOKEN";
export const INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN";
export const NO_API_KEY_PROVIDED = "NO_API_KEY_PROVIDED";
export const INVALID_API_KEY = "INVALID_API_KEY";
export const NO_USER_WITH_USERID = "NO_USER_WITH_USERID";
